# Generated by Django 5.1.6 on 2025-03-06 10:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RegisterCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("registraition_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PendingRegistrationApproval", "Đang chờ duyệt đăng kí"),
                            ("RegistrationSuccessful", "Đăng kí thành công"),
                            ("RegistrationNotApproved", "Không được duyệt đăng kí"),
                            ("PendingRefundApproval", "Đang chờ duyệt hoàn tiền"),
                            ("RefundSuccessful", "Hoàn tiền thành công"),
                            ("RefundNotApproved", "Không được duyệt hoàn tiền"),
                        ],
                        default="PendingRegistrationApproval",
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    "course_fee_at_registration",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("tuition_fee", models.DecimalField(decimal_places=2, max_digits=15)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_end_date", models.DateField()),
                ("lesson_count", models.IntegerField(default=0, editable=False)),
                ("exercise_count", models.IntegerField(default=0, editable=False)),
                (
                    "status",
                    models.CharField(default="active", editable=False, max_length=50),
                ),
                (
                    "current_student_count",
                    models.IntegerField(default=0, editable=False),
                ),
                ("registration_deadline", models.DateField()),
                ("graduation_date", models.DateField()),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("announcement", models.TextField(blank=True, null=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=-1, editable=False, max_digits=3
                    ),
                ),
                ("img", models.ImageField(upload_to="img_course/")),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.manager"
                    ),
                ),
                ("teachers", models.ManyToManyField(to="user.teacher")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="course.subject"
                    ),
                ),
            ],
        ),
    ]
