# Generated by Django 5.1.6 on 2025-03-20 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_registercourse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegisterCourse",
        ),
    ]
