# Generated by Django 5.1.6 on 2025-03-20 14:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_delete_registercourse"),
        ("user", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterCourse",
            fields=[
                (
                    "id_register_course",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("registraition_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PendingRegistrationApproval", "Đang chờ duyệt đăng kí"),
                            ("RegistrationSuccessful", "Đăng kí thành công"),
                            ("RegistrationNotApproved", "Không được duyệt đăng kí"),
                            ("PendingRefundApproval", "Đang chờ duyệt hoàn tiền"),
                            ("RefundSuccessful", "Hoàn tiền thành công"),
                            ("RefundNotApproved", "Không được duyệt hoàn tiền"),
                        ],
                        default="PendingRegistrationApproval",
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    "course_fee_at_registration",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_course",
                        to="user.student",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_student",
                        to="user.student",
                    ),
                ),
            ],
        ),
    ]
