# Generated by Django 5.1.6 on 2025-03-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_registercourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registercourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registered_course",
                to="course.course",
            ),
        ),
    ]
