# Generated by Django 5.1.6 on 2025-03-21 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_alter_registercourse_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="id_course",
            new_name="id",
        ),
    ]
