# Generated by Django 5.1.6 on 2025-03-24 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_rename_id_course_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="registercourse",
            name="course_fee_at_registration",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
