# Generated by Django 5.1.6 on 2025-03-24 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_alter_course_tuition_fee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registercourse",
            old_name="id_register_course",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="id_subject",
            new_name="id",
        ),
    ]
