# Generated by Django 5.1.6 on 2025-03-25 00:55

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0008_rename_id_register_course_registercourse_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registercourse",
            name="course_fee_at_registration",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[course.models.CustomMinValueValidator(0.0)],
            ),
        ),
    ]
