# Generated by Django 5.1.6 on 2025-03-07 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="date_of_birth",
            new_name="date_of_birthT",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="phone_number",
            new_name="phone_numberT",
        ),
    ]
