# Generated by Django 5.1.6 on 2025-03-22 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_student_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="workplace",
            new_name="work_place",
        ),
    ]
