# Generated by Django 5.1.6 on 2025-03-22 05:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_rename_workplace_teacher_work_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="professional_certification",
        ),
    ]
