# Generated by Django 5.1.6 on 2025-03-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_teacher_professional_certification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="student_rating",
        ),
        migrations.AddField(
            model_name="student",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(default="2002-03-03"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(default="0379870898", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/Anh_man_hinh_2025-02-13_luc_06.57.29.png",
                upload_to="profile_pics/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="academic_degree",
            field=models.CharField(default="thac si", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="date_of_birthT",
            field=models.DateField(default="2002-03-03"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone_numberT",
            field=models.CharField(default="03798239238", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/img5.jpeg", upload_to="profile_pics/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="specialty",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacher",
            name="work_place",
            field=models.CharField(default="can tho", max_length=255),
            preserve_default=False,
        ),
    ]
