# Generated by Django 5.1.6 on 2025-03-22 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_remove_teacher_student_rating_student_sex_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="date_of_birthT",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="phone_numberT",
            new_name="phone_number",
        ),
    ]
